# Generated by Django 3.2.7 on 2021-12-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0002_auto_20211226_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dietApp.profile')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories', models.IntegerField()),
                ('burnt', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('proteins', models.IntegerField()),
            ],
        ),
    ]
