# Generated by Django 3.2.7 on 2021-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0003_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories', models.IntegerField()),
                ('burnt', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('proteins', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='profile',
            name='days',
            field=models.ManyToManyField(to='dietApp.Say'),
        ),
    ]
