# Generated by Django 3.2.7 on 2021-12-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0004_auto_20211231_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Say',
            new_name='Fragment',
        ),
    ]
