# Generated by Django 3.2.7 on 2022-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0005_rename_say_fragment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='date',
            field=models.DateField(),
        ),
    ]
